Add pre-commit hooks and update code to pass stylua and shellcheck

diff --git a/bin/run-command-on-git-revisions b/bin/run-command-on-git-revisions
--- a/bin/run-command-on-git-revisions
+++ b/bin/run-command-on-git-revisions
@@ -10,11 +10,13 @@
 # Example usage:
 #   $ run-command-on-git-revisions origin/master master 'python runtests.py'
 
-set -e
+set -eu
 
 if [[ $1 == -v ]]; then
-    verbose=1
-    shift
+  verbose=1
+  shift
+else
+  verbose=0
 fi
 
 start_ref=$1
@@ -22,64 +24,61 @@ end_ref=$2
 test_command=$3
 
 main() {
-    abort_if_dirty_repo
-    enforce_usage
-    run_tests
+  abort_if_dirty_repo
+  enforce_usage
+  run_tests
 }
 
 abort_if_dirty_repo() {
-    set +e
-    git diff-index --quiet --cached HEAD
-    if [[ $? -ne 0 ]]; then
-        echo "You have staged but not committed changes that would be lost! Aborting."
-        exit 1
-    fi
-    git diff-files --quiet
-    if [[ $? -ne 0 ]]; then
-        echo "You have unstaged changes that would be lost! Aborting."
-        exit 1
-    fi
-    untracked=$(git ls-files --exclude-standard --others)
-    if [ -n "$untracked" ]; then
-        echo "You have untracked files that could be overwritten! Aborting."
-        exit 1
-    fi
-    set -e
+  set +e
+  if ! git diff-index --quiet --cached HEAD; then
+    echo "You have staged but not committed changes that would be lost! Aborting."
+    exit 1
+  fi
+  if ! git diff-files --quiet; then
+    echo "You have unstaged changes that would be lost! Aborting."
+    exit 1
+  fi
+  untracked=$(git ls-files --exclude-standard --others)
+  if [ -n "$untracked" ]; then
+    echo "You have untracked files that could be overwritten! Aborting."
+    exit 1
+  fi
+  set -e
 }
 
 enforce_usage() {
-    if [ -z "$test_command" ]; then
-        usage
-        exit 1
-    fi
+  if [ -z "$test_command" ]; then
+    usage
+    exit 1
+  fi
 }
 
 usage() {
-    echo "usage: `basename $0` start_ref end_ref test_command"
+  echo "usage: $(basename "$0") start_ref end_ref test_command"
 }
 
 run_tests() {
-    revs=`log_command git rev-list --reverse ${start_ref}..${end_ref}`
-
-    for rev in $revs; do
-        debug "Checking out: $(git log --oneline -1 $rev)"
-        log_command git checkout --quiet $rev
-        log_command $test_command
-        log_command git reset --hard --quiet
-    done
-    log_command git checkout --quiet $end_ref
-    debug "OK for all revisions!"
+  revs=$(log_command git rev-list --reverse "${start_ref}..${end_ref}")
+  for rev in $revs; do
+    debug "Checking out: $(git log --oneline -1 "$rev")"
+    log_command git checkout --quiet "$rev"
+    log_command "$test_command"
+    log_command git reset --hard --quiet
+  done
+  log_command git checkout --quiet "$end_ref"
+  debug "OK for all revisions!"
 }
 
 log_command() {
-    debug "=> $*"
-    eval "$@"
+  debug "=> $*"
+  eval "$*"
 }
 
 debug() {
-    if [ $verbose ]; then
-        echo $* >&2
-    fi
+  if [ $verbose == 1 ]; then
+    echo "$@" >&2
+  fi
 }
 
 main
